---
- hosts:
  - 127.0.0.1
  connection: local
  gather_facts: False
  vars_files:
    - vars/ec2.yml
  tasks:
  - name: Lauch new EC2 instance
    local_action: ec2
      keypair={{ec2_keypair}}
      group={{ec2_security_group}}
      instance_type={{ec2_instance_type}}
      image={{ec2_image}}
      wait=true
      region=sa-east-1
    register: ec2 
  - name: Waiting for ssh service 
    local_action: wait_for
      delay=10
      port=22
      state=started
      host={{ item.public_ip }}
      timeout=120
    with_items: ec2.instances
  - name: Register instance 
    local_action: add_host 
      hostname={{ item.public_ip }} 
      groupname=cloudexam-exam-created 
    with_items: ec2.instances

- hosts: cloudexam-exam-created
  user: "{{ ec2_user }}" 
  gather_facts: True
  vars_files:
    - vars/ec2.yml
  tasks:
  - name: Install git
    apt: 
       name=git
       state=present
    sudo: true 
  - name: Creating folder where project will be
    shell: mkdir ephemeral 
    args: 
      chdir: /
    sudo: true
  - name: Clonning repository
    git: 
      repo=https://github.com/cloudson/cloudexam-exam.git
      dest=/ephemeral/cloudexam-exam
    register: git
    sudo: true
  - name: Owner of cloudexam folder should be www-data
    shell: chown -R www-data:www-data * 
    args:
      chdir: /ephemeral
    sudo: true
  - name: Install apache2 
    apt:
      name=apache2
      state=present
    sudo: true
  - name: Create virtualhost file 
    shell: sed -i 's;yourdirectory;ephemeral\/cloudexam-exam;g' cloudexam-exam.conf
    args:
      chdir: /ephemeral/cloudexam-exam/docs
    sudo: true
  - shell: mv cloudexam-exam.conf /etc/apache2/sites-enabled/
    args:
      chdir: /ephemeral/cloudexam-exam/docs
    sudo: true
  - name: Run server 
    shell: echo "127.0.0.1 " 
  - shell: service apache2 restart
    sudo: true

